name: Check PR

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('**/npm-shrinkwrap.json') }}
      - name: Restore dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}-${{ matrix.node }}
          path: |
            .
            !node_modules
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]
        include:
          - node: 10
            os: macos-latest
          - node: 12
            os: macos-latest

    steps:
      - uses: actions/download-artifact@v2
        if: ${{ matrix.node == 14 }}
        with:
          name: build-${{ matrix.os }}-${{ matrix.node }}
      - uses: actions/download-artifact@v2
        if: ${{ matrix.node != 14 }}
        with:
          name: build-${{ matrix.os }}-14
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('**/npm-shrinkwrap.json') }}
      - name: Restore dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        if: ${{ matrix.node == 14 }}
        run: npm test
      - name: Test
        if: ${{ matrix.node != 14 }}
        run: npm run test:nocov
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.node }}
          path: coverage
  
